# -*- coding: utf-8 -*-
"""Control semana 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18_6dfwBrb7dNU3YRFRJv2vMAQoHBU1jH

1 Taller Semana 3<br>
Problema<br>
Una botillería vende y despacha 6.000 cervezas diarias, se sabe que cada cerveza por diversos inconventientes del despacho tiene un 4% de probabilidad de sufrir un desperfecto y ser devuelta a
la botillería. <br> Determine:<br>
<ol><li> El número esperado y desviación típica de cervezas despachadas que si son recibidas en un día.</li>
<li>La probabilidad de tener más de 5.850 cervezas despachas en un día (resuelva esta pregunta aplicando el modelo binomial, poisson y normal).</li><li>
¿Qué puede concluir de la respuesta anterior y el uso de los tres modelos?</li>
"""

from statsmodels.distributions.empirical_distribution import ECDF
import scipy.stats as stats
import numpy as np
import math

import random

def media(n, p):
  return n*p

def varianza(n, p):
  return media(n,p)*(1-p)

def desviacion(n, p):
  return varianza(n, p) ** 0.5


#ejercicio 1
# condicion fav: no tener desperfecto

casos_totales = 6000
error = 0.04
exito =  1 - error

casos_favorables = 6000 * (exito)
print("Ejercicio 1\n============")
print("Casos favorables:\t" + str(casos_favorables))
print("Casos error:\t\t" + str(6000 * error))
print("Desviación: \t\t"+ str(desviacion(casos_totales, exito)))
print("\n")
print("Ejercicio 2\n============")
x = 5850
binom_ = stats.binom.cdf(x+1, casos_totales, exito) #al menos 5850
print("Distr. Binomial:\t"+str(binom_))

#x = nro de botellas x dia
poisson_ = stats.poisson(media(casos_totales, exito)).cdf(x)
print("Distr. Poisson:\t\t"+str(poisson_))

normal_ = stats.norm.cdf(x, loc=0, scale=1000)
print("Distr. Normal:\t\t"+str(normal_))

# Concl.
print("\n")
print("Ejercicio 3 (Conculsión)\n========================")
print("Las probabilidades tienen distinto grado de variación dependiendo del tipo\n" +
"de distribución que se emplea, así mismo también la precisión respecto a la cantidad\n" +
"de valores de la misma, por ejemplo, si aplicamos una escala diferente en la\n" +
"distribucion normal, se obtienen una variacion en la probasbilidad")
