# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhVr_IYiSD7_ghoSh3gNuR_BHoReHqzG
"""

!pip install scipy

from scipy.stats import norm

def calcular_valor_z(percentil):
    # Utilizamos el método ppf (percent point function) de scipy.stats.norm
    # para obtener el valor Z dado un percentil.
    # Por ejemplo, percentil 0.90 corresponde al 90% y percentil 0.95 corresponde al 95%.
    valor_z = norm.ppf(percentil)
    return valor_z

# Ejemplo: Calcular el valor Z para el 90% (percentil 0.90)
percentil_90 = 0.90
valor_z_90 = calcular_valor_z(percentil_90)
print("Valor Z para el 90%:", valor_z_90)

# Ejemplo: Calcular el valor Z para el 95% (percentil 0.95)
percentil_95 = 0.95
valor_z_95 = calcular_valor_z(percentil_95)
print("Valor Z para el 95%:", valor_z_95)