# -*- coding: utf-8 -*-
"""clase semana 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dzjepBSDGJB_QtwvzA4pzb0RYy_p4U0
"""

import scipy.stats as stats
#para a < x < b
minimo = 6
maximo = 10
l = 4
timepo = 1.5
lambda_ = l*timepo #coincidencia con el minimo
a = stats.poisson(lambda_).cdf(maximo-1) # P(x<10)
b = stats.poisson(lambda_).cdf(minimo) # P(x<=6)
print(a-b)
################################################################
timepo2 = 0.75
lambda2_ = l * timepo2
tope = 3

a = 1 - (stats.poisson(lambda2_).cdf(tope-1)) # P(x>=3)
print(a)



import scipy.stats as stats
print( stats.norm.ppf(0.88))

#(x, mu, sigma)
a = stats.norm.cdf(160, 140, 10)
print(1 -a)

print( stats.norm.ppf(0.95))