library(readxl)
library(dplyr)
library(ggplot2)
library(ggcorrplot)
library(e1071)
library(ROCR)
library(class)
library(rpart)
library(randomForest)
library(reshape)
library(kknn)
library(psych)
data <- read_excel("BBDD_EPA_NIVELES_ABSTRACCION_CLASS-Minaría_de_dato
s.xlsx")
View(data)
head(data)